# Generated by Django 6.0 on 2025-12-21 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rejs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('od', models.DateField(verbose_name='data od')),
                ('do', models.DateField(verbose_name='data do')),
                ('start', models.CharField(max_length=200, verbose_name='port początkowy')),
                ('koniec', models.CharField(max_length=200, verbose_name='port końcowy')),
                ('cena', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('zaliczka', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('opis', models.TextField(default='tutaj opis rejsu')),
            ],
            options={
                'verbose_name': 'Rejs',
                'verbose_name_plural': 'Rejsy',
            },
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tytul', models.CharField(default='nowe ogłoszenie', max_length=100, verbose_name='Tytuł')),
                ('text', models.TextField(default='krótka informacja o rejsie', verbose_name='Tekst')),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogloszenia', to='rejs.rejs')),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
            },
        ),
        migrations.CreateModel(
            name='Wachta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wachty', to='rejs.rejs')),
            ],
            options={
                'verbose_name': 'Wachta',
                'verbose_name_plural': 'Wachty',
            },
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('telefon', models.CharField(max_length=15, verbose_name='Numer telefonu')),
                ('status', models.CharField(choices=[('QUALIFIED', 'Zakwalifikowany'), ('NOT_QUALIFIED', 'Niezakwalifikowany'), ('ODRZUCONE', 'Odrzucone')], default=('NOT_QUALIFIED', 'Niezakwalifikowany'), max_length=200)),
                ('wzrok', models.CharField(choices=[('WIDZI', 'widzący'), ('NIEWIDOMY', 'niewidomy'), ('SLABO-WIDZACY', 'słabo widzący')], default=('WIDZI', 'widzący'), max_length=15, verbose_name='Status wzroku')),
                ('rola', models.CharField(choices=[('ZALOGANT', 'załogant'), ('OFICER-WACHTY', 'oficer wachty')], default='ZALOGANT', max_length=25)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zgloszenia', to='rejs.rejs')),
                ('wachta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='czlonkowie', to='rejs.wachta')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
            },
        ),
        migrations.CreateModel(
            name='Wplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('rodzaj', models.CharField(choices=[('wplata', 'Wpłata'), ('zwrot', 'Zwrot')], default=('zwrot', 'Zwrot'), max_length=7)),
                ('zgloszenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wplaty', to='rejs.zgloszenie')),
            ],
            options={
                'verbose_name': 'Wpłata',
                'verbose_name_plural': 'Wpłaty',
            },
        ),
    ]
