# Generated by Django 6.0 on 2025-12-28 09:11

import django.db.models.deletion
import rejs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rejs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('od', models.DateField(verbose_name='data od')),
                ('do', models.DateField(verbose_name='data do')),
                ('start', models.CharField(max_length=200, verbose_name='port początkowy')),
                ('koniec', models.CharField(max_length=200, verbose_name='port końcowy')),
                ('cena', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('zaliczka', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('opis', models.TextField(default='tutaj opis rejsu')),
                ('aktywna_rekrutacja', models.BooleanField(default=True, verbose_name='aktywna rekrutacja')),
            ],
            options={
                'verbose_name': 'Rejs',
                'verbose_name_plural': 'Rejsy',
            },
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tytul', models.CharField(default='nowe ogłoszenie', max_length=100, verbose_name='Tytuł')),
                ('text', models.TextField(default='krótka informacja o rejsie', verbose_name='Tekst')),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogloszenia', to='rejs.rejs')),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
            },
        ),
        migrations.CreateModel(
            name='Wachta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wachty', to='rejs.rejs')),
            ],
            options={
                'verbose_name': 'Wachta',
                'verbose_name_plural': 'Wachty',
            },
        ),
        migrations.CreateModel(
            name='Zgloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('telefon', models.CharField(max_length=15, verbose_name='Numer telefonu')),
                ('data_urodzenia', models.DateField(verbose_name='data urodzenia')),
                ('adres', models.CharField(default='unknown')),
                ('kod_pocztowy', models.CharField(default='00-000', verbose_name='kod pocztowy')),
                ('miejscowosc', models.CharField(default='unknown')),
                ('obecnosc', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=3, verbose_name='uczestnictwo w zobaczyć morze')),
                ('rodo', models.BooleanField(help_text='zgadzam się na przetwarzanie danych osobowych zgodnie z polityką prywatności zobaczyć morze.', verbose_name='zgoda na przetwarzanie danych osobowych')),
                ('status', models.CharField(choices=[('Niezakwalifikowany', 'Niezakwalifikowany'), ('Zakwalifikowany', 'Zakwalifikowany'), ('Odrzucone', 'Odrzucone')], default='Niezakwalifikowany', max_length=200)),
                ('wzrok', models.CharField(choices=[('WIDZI', 'widzący'), ('NIEWIDOMY', 'niewidomy'), ('SLABO-WIDZACY', 'słabo widzący')], default=('WIDZI', 'widzący'), max_length=15, verbose_name='Status wzroku')),
                ('rola', models.CharField(choices=[('ZALOGANT', 'załogant'), ('OFICER-WACHTY', 'oficer wachty')], default='ZALOGANT', max_length=25)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_zgloszenia', models.DateTimeField(auto_now_add=True)),
                ('rejs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zgloszenia', to='rejs.rejs')),
                ('wachta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='czlonkowie', to='rejs.wachta')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
            },
        ),
        migrations.CreateModel(
            name='Wplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('rodzaj', models.CharField(choices=[('wplata', 'Wpłata'), ('zwrot', 'Zwrot')], default=('zwrot', 'Zwrot'), max_length=7)),
                ('zgloszenie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wplaty', to='rejs.zgloszenie')),
            ],
            options={
                'verbose_name': 'Wpłata',
                'verbose_name_plural': 'Wpłaty',
            },
        ),
        migrations.CreateModel(
            name='Dane_Dodatkowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poz1', rejs.models.EncryptedTextField(default='12345678900', max_length=13, verbose_name='pesel')),
                ('poz2', rejs.models.EncryptedTextField(choices=[('paszport', 'paszport'), ('dowod-osobisty', 'dowód osobisty')], default=('paszport', 'paszport'), max_length=14, verbose_name='typ dokumentu')),
                ('poz3', rejs.models.EncryptedTextField(default='ABC123', verbose_name='numer dokumentu')),
                ('zgloszenie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dane_dodatkowe', to='rejs.zgloszenie')),
            ],
            options={
                'verbose_name': 'dane dodatkowe',
                'verbose_name_plural': 'dane dodatkowe',
                'permissions': [('export_sensitive_data', 'Może eksportować dane wrażliwe do raportów')],
            },
        ),
        migrations.AddConstraint(
            model_name='zgloszenie',
            constraint=models.UniqueConstraint(fields=('rejs', 'imie', 'nazwisko', 'email'), name='unique_zgloszenie_na_rejs_dla_osoby'),
        ),
    ]
